author:
  name:           "Susanna Pozzoli"
  url:            https://twitter.com/snnpzz
description:      "CS PhD Student @ KTH"
google_analytics: G-WRXEFS3BQQ
paginate:         5
title:            "@snnpzz"
url:              https://snnpzz.github.io

sass:
  sass_dir:       _sass

# Conversion
markdown:         redcarpet
highlighter:      pygments

# Serving
baseurl:          /

# Outputting
permalink:        pretty
